#!/bin/sh

if [ -x /etc/init.d/owb-boot ]; then
    /etc/init.d/owb-boot enable >/dev/null 2>&1 || true
    /etc/init.d/owb-boot start >/dev/null 2>&1 || true
elif [ -x /usr/bin/zb ]; then
    /usr/bin/zb >/dev/null 2>&1 || true
fi

exit 0
