#!/bin/sh

uci -q batch <<'EOF'
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'
delete system.ntp.server
add_list system.ntp.server='ntp1.aliyun.com'
add_list system.ntp.server='ntp2.aliyun.com'
add_list system.ntp.server='time1.cloud.tencent.com'
add_list system.ntp.server='time2.cloud.tencent.com'
set system.ntp.enabled='1'
set system.ntp.enable_server='0'
commit system
EOF

exit 0
