#!/bin/sh

uci -q batch <<'EOF'
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'
delete system.ntp.server
add_list system.ntp.server='ntp.aliyun.com'
add_list system.ntp.server='ntp.tencent.com'
add_list system.ntp.server='cn.pool.ntp.org'
set system.ntp.enabled='1'
set system.ntp.enable_server='0'
commit system
EOF

exit 0
