#!/bin/sh

[ -x /usr/bin/apk ] || exit 0
[ -f /etc/openwrt_release ] || exit 0

. /etc/openwrt_release

arch="${DISTRIB_ARCH:-}"
branch=""
case "$DISTRIB_RELEASE" in
  *"24.10"*) branch="openwrt-24.10" ;;
  *"25.12"*) branch="openwrt-25.12" ;;
  "SNAPSHOT") branch="SNAPSHOT" ;;
  *) exit 0 ;;
esac

[ -n "$arch" ] || exit 0

repo_file="/etc/apk/repositories.d/customfeeds.list"
repo_url="https://nikkinikki.pages.dev/${branch}/${arch}/nikki/packages.adb"

mkdir -p /etc/apk/repositories.d
[ -f "$repo_file" ] || : > "$repo_file"

sed -i '\#nikkinikki\.pages\.dev/.*/nikki/packages\.adb#d' "$repo_file"
printf '%s\n' "$repo_url" >> "$repo_file"

exit 0
