OPENWRT_TARGET=x86
OPENWRT_SUBTARGET=64
OPENWRT_PROFILE=generic
OPENWRT_FS=squashfs
OPENWRT_IMAGES="combined-efi.img.gz"
ROOTFS_PARTSIZE=1024
BUILD_BASE=https://downloads.openwrt.org
PACKAGES_FILE=config/packages.list
